package com.vortex.a3.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.compositionLocalOf

/**
 * Minimal Compose-friendly i18n: one CompositionLocal carries the active
 * locale; each composable reads the string via [str]. The translations
 * keys mirror those of the Tauri side (src/lib/locales) so the
 * two UIs stay aligned.
 *
 * No Android resource layer — switching locale just re-emits the
 * CompositionLocal and Compose recomposes automatically; no Activity
 * recreate, no AppCompat dependency.
 */
enum class VortexLocale(val code: String, val label: String) {
    Uzbek("uz", "O'zbekcha"),
    English("en", "English"),
    Russian("ru", "Русский");

    companion object {
        fun fromCode(code: String): VortexLocale =
            entries.firstOrNull { it.code == code } ?: English
    }
}

val LocalVortexLocale = compositionLocalOf { VortexLocale.English }

@Composable
@ReadOnlyComposable
fun str(key: String, vararg args: Any): String {
    val locale = LocalVortexLocale.current
    val raw = STRINGS[locale]?.get(key) ?: STRINGS[VortexLocale.English]?.get(key) ?: key
    return if (args.isEmpty()) raw else raw.format(*args)
}

private val EN = mapOf(
    "app.title"            to "Vortex",
    "app.tagline"          to "Secure bridge between your Linux and Android",
    "device.this"          to "This device",
    "device.linux"         to "Linux laptop",
    "device.android"       to "Android phone",
    "device.earbuds"       to "Earbuds",
    "device.paired_badge"  to "%d paired",
    "device.loading"       to "loading identity…",
    "peers.title"          to "Paired devices",
    "peers.empty"          to "No devices yet. Open Vortex on your Linux laptop — it will appear here automatically.",
    "peers.forget_all"     to "Forget all",
    "peers.online"         to "Connected",
    "peers.offline"        to "Disconnected",
    "peers.forget_title"   to "Forget device",
    "peers.forget_body"    to "Stop trusting %s? You'll need to re-pair to connect again.",
    "peers.forget_confirm" to "Forget",
    "earbuds.not_connected" to "Not connected",
    "earbuds.on_local"     to "Connected here",
    "earbuds.on_peer"      to "Connected to laptop",
    "earbuds.use_here"     to "Use on this phone",
    "earbuds.handoff_soon" to "Handoff coming soon",
    "earbuds.add"          to "Add earbuds",
    "earbuds.add_hint"     to "Tap to pick a device",
    "earbuds.add_modal_hint" to "Pick the Bluetooth device you'd like Vortex to track. It stays on your home screen even when disconnected.",
    "earbuds.scanning"     to "Scanning nearby Bluetooth…",
    "earbuds.scan_done"    to "Pick a device",
    "earbuds.scan_empty"   to "No Bluetooth devices found. Put your earbuds in pairing mode and rescan.",
    "earbuds.rescan"       to "Rescan",
    "earbuds.now_connected" to "connected",
    "earbuds.remove"       to "Remove from Vortex",
    "earbuds.remove_body"  to "The earbuds card will go away. Your Bluetooth pairing on this device is left untouched.",
    "earbuds.long_press_hint" to "Long-press to remove",
    "switch.bring_title"   to "Bring earbuds here?",
    "switch.bring_body"    to "The laptop will release them, then this phone will connect.",
    "switch.bring_confirm" to "Bring to me",
    "switch.send_title"    to "Send earbuds to laptop?",
    "switch.send_body"     to "This phone will release them, then the laptop will connect.",
    "switch.send_confirm"  to "Send to laptop",
    "switch.cancel"        to "Cancel",
    "cast.kind_title"      to "Show the laptop screen",
    "cast.kind_extend"     to "Extended display",
    "cast.kind_extend_hint" to "A second screen for the laptop — drag windows onto this phone",
    "cast.kind_mirror"     to "Screen mirroring",
    "cast.kind_mirror_hint" to "Watch what is already on the laptop screen",
    "switch.send_menu"     to "Send to laptop",
    "switch.in_progress"   to "Switching…",
    "switch.failed"        to "Switch failed: %s",
    "scan.close"           to "Close",
    "discover.title"       to "Discovery",
    "discover.discoverable" to "Discoverable",
    "discover.discoverable_hint" to "Open Vortex on your Linux laptop nearby.",
    "discover.idle"         to "Tap Start to be discoverable again.",
    "pair.start"           to "Start pairing",
    "pair.resume"          to "Resume advertising",
    "pair.stop"            to "Stop",
    "pair.stop_window"     to "Stop pairing window",
    "pair.starting"        to "Starting…",
    "pair.try_again"       to "Try again",
    "pair.caption_idle"    to "Background service active in trusted-presence mode.",
    "pair.caption_no_trust" to "Tap to broadcast a 60-second pairing window.",
    "pair.caption_starting" to "Bringing up GATT server…",
    "pair.caption_window"   to "Pairing window open. Find this device from your Linux laptop.",
    "pair.caption_presence" to "Reachable to paired peers • rotating private token every 60s.",
    "pair.error"            to "Error: %s",
    "sas.title"             to "Pairing request",
    "sas.body"              to "A Linux device wants to pair with this phone. Make sure these three emoji match the ones on your laptop, then approve.",
    "sas.approve"           to "Approve",
    "sas.reject"            to "Reject",
    "hint.bluetooth_off"    to "Bluetooth is off — Vortex links over low-power Bluetooth (it won't drain your battery). Turn it on to connect.",
    "hint.bluetooth_off_action" to "Turn on Bluetooth",
    "hint.battery"          to "Battery optimization is on — Android may kill the Vortex service when the screen sleeps.",
    "hint.battery_action"   to "Allow background activity",
    "hint.autostart"        to "On Xiaomi, Samsung, Huawei and similar phones, allow Vortex to auto-start (or mark it “never sleeping”) so it reconnects and stays linked after reboot.",
    "hint.autostart_action" to "Open Autostart settings",
    "hint.notif_access"     to "Grant notification access so Vortex can detect what's playing and switch the earbuds precisely (it falls back to a coarser detector otherwise).",
    "hint.notif_access_action" to "Grant notification access",
    "common.later"          to "Later",
    "notes.title"           to "Notes",
    "notes.all"             to "All",
    "notes.notes"           to "Notes",
    "notes.todos"           to "Todos",
    "notes.new_note"        to "New note",
    "notes.new_todo"        to "New todo",
    "notes.empty"           to "No notes yet",
    "notes.untitled"        to "Untitled",
    "notes.title_placeholder" to "Title",
    "notes.todo_placeholder"  to "What needs doing?",
    "notes.body_placeholder"  to "Write something…",
    "notes.delete"          to "Delete",
    "notes.add_reminder"    to "Add reminder",
    "notes.clear_reminder"  to "Clear reminder",
    "notes.add_todo"        to "Add a to-do",
    "notes.empty_todos"     to "No to-dos yet",
    "notes.todos_done"      to "%d of %d done",
    "notes.tap_complete"    to "Tap a circle to complete",
    "hint.dismiss"          to "Got it",
    "settings.title"        to "Settings",
    "settings.sec_appearance" to "Appearance",
    "settings.sec_continuity" to "Continuity",
    "settings.sec_device"     to "Device",
    "settings.language"     to "Language",
    "settings.theme"        to "Theme",
    "settings.theme_dark"   to "Dark",
    "settings.theme_light"  to "Light",
    "settings.smart_switch"      to "Smart audio-follow",
    "settings.smart_switch_hint" to "Move the earbuds to whichever device starts playing",
    "settings.notif_mirror"      to "Notification mirroring",
    "settings.notif_mirror_hint" to "Show this phone's notifications on the laptop",
    "settings.peer_notif"        to "Laptop notifications",
    "settings.peer_notif_hint"   to "Show the laptop's notifications on this phone",
    "settings.clipboard_sync"       to "Clipboard sync",
    "settings.clipboard_sync_hint"  to "Share copied text both ways with the laptop",
    "settings.file_auto_accept"      to "Auto-accept files from laptop",
    "settings.file_auto_accept_hint" to "Save files sent by the laptop without asking. Only your paired laptop can send them.",
    "settings.clipboard_adb_title"  to "Make phone→laptop automatic",
    "settings.clipboard_adb_body"   to "Android blocks background clipboard reads. Run this once from a computer (USB debugging on) to copy without the Quick Settings tile:",
    "settings.clipboard_auto_on"    to "Automatic — copies sync without the tile",
    "settings.on"           to "On",
    "settings.off"          to "Off",
    "settings.done"         to "Done",
)

private val UZ = mapOf(
    "app.title"            to "Vortex",
    "app.tagline"          to "Linux va Android orasidagi xavfsiz ko'prik",
    "device.this"          to "Bu qurilma",
    "device.linux"         to "Linux noutbuk",
    "device.android"       to "Android telefon",
    "device.earbuds"       to "Quloqchin",
    "device.paired_badge"  to "%d ta ulangan",
    "device.loading"       to "kimligi yuklanmoqda…",
    "peers.title"          to "Juftlangan qurilmalar",
    "peers.empty"          to "Hozircha qurilma yo'q. Yonidagi Linux'da Vortex'ni oching — bu yerda avtomatik paydo bo'ladi.",
    "peers.forget_all"     to "Hammasini unutish",
    "peers.online"         to "Ulangan",
    "peers.offline"        to "Ulanmagan",
    "peers.forget_title"   to "Qurilmani unutish",
    "peers.forget_body"    to "%s bilan aloqa uziladi. Qayta ulanish uchun yana pairing qilinadi.",
    "peers.forget_confirm" to "Unutish",
    "earbuds.not_connected" to "Ulangmagan",
    "earbuds.on_local"     to "Bu telefonga ulangan",
    "earbuds.on_peer"      to "Noutbukka ulangan",
    "earbuds.use_here"     to "Bu telefonda eshitish",
    "earbuds.handoff_soon" to "Tezda qo'shiladi",
    "earbuds.add"          to "Quloqchin qo'shish",
    "earbuds.add_hint"     to "Qurilma tanlash uchun bosing",
    "earbuds.add_modal_hint" to "Vortex kuzatadigan Bluetooth qurilmasini tanlang. U ulanmagan paytda ham home ekranda turaveradi.",
    "earbuds.scanning"     to "Yaqindagi Bluetooth qidirilmoqda…",
    "earbuds.scan_done"    to "Qurilmani tanlang",
    "earbuds.scan_empty"   to "Bluetooth qurilma topilmadi. Quloqchinni pairing rejimiga qo'yib qayta qidiring.",
    "earbuds.rescan"       to "Qayta qidirish",
    "earbuds.now_connected" to "ulangan",
    "earbuds.remove"       to "Vortex'dan o'chirish",
    "earbuds.remove_body"  to "Quloqchin kartasi yo'qoladi. Bluetooth pairing'ingiz tegmaydi.",
    "earbuds.long_press_hint" to "O'chirish uchun uzoq bosing",
    "switch.bring_title"   to "Quloqchinni bu yerga olamizmi?",
    "switch.bring_body"    to "Noutbuk uni qo'yib yuboradi, keyin bu telefon ulanadi.",
    "switch.bring_confirm" to "Bu telefonga",
    "switch.send_title"    to "Quloqchinni noutbukka yuborilsinmi?",
    "switch.send_body"     to "Telefon qo'yib yuboradi, keyin noutbuk ulanadi.",
    "switch.send_confirm"  to "Noutbukka yuborish",
    "switch.cancel"        to "Bekor qilish",
    "cast.kind_title"      to "Noutbuk ekranini ko'rsatish",
    "cast.kind_extend"     to "Qo'shimcha ekran",
    "cast.kind_extend_hint" to "Noutbuk uchun ikkinchi ekran — oynalarni shu telefonga sudrab olib o'tasiz",
    "cast.kind_mirror"     to "Ekran oynasi",
    "cast.kind_mirror_hint" to "Noutbuk ekranida hozir turgan narsani ko'rasiz",
    "switch.send_menu"     to "Noutbukka yuborish",
    "switch.in_progress"   to "Almashtirilmoqda…",
    "switch.failed"        to "Almashtirish bo'lmadi: %s",
    "scan.close"           to "Yopish",
    "discover.title"       to "Topishuv",
    "discover.discoverable" to "Topiladigan",
    "discover.discoverable_hint" to "Yonidagi Linux noutbukda Vortex'ni oching.",
    "discover.idle"         to "Topiladigan bo'lish uchun Boshlashni bosing.",
    "pair.start"           to "Boshlash",
    "pair.resume"          to "Davom etish",
    "pair.stop"            to "To'xtatish",
    "pair.stop_window"     to "Oynani yopish",
    "pair.starting"        to "Boshlanmoqda…",
    "pair.try_again"       to "Qayta urinish",
    "pair.caption_idle"    to "Fon xizmati ishonchli-tanish rejimida ishlamoqda.",
    "pair.caption_no_trust" to "60 sekundlik pairing oynasini ochish uchun bosing.",
    "pair.caption_starting" to "GATT server ko'tarilmoqda…",
    "pair.caption_window"   to "Pairing oynasi ochiq. Linux noutbukda bu qurilmani toping.",
    "pair.caption_presence" to "Juftlangan qurilmalarga ko'rinmoqda • har 60s yangi maxfiy token.",
    "pair.error"            to "Xato: %s",
    "sas.title"             to "Pairing so'rovi",
    "sas.body"              to "Linux qurilmasi bu telefon bilan juftlanmoqchi. Quyidagi 3 emoji laptopdagisi bilan mos kelishini tekshirib, tasdiqlang.",
    "sas.approve"           to "Tasdiqlash",
    "sas.reject"            to "Rad etish",
    "hint.bluetooth_off"    to "Bluetooth o'chiq — Vortex past-quvvatli Bluetooth orqali ulanadi (batareyani yemaydi). Ulanish uchun yoqing.",
    "hint.bluetooth_off_action" to "Bluetooth'ni yoqish",
    "hint.battery"          to "Batareya optimizatsiyasi yoqilgan — ekran o'chsa Android Vortex xizmatini to'xtatishi mumkin.",
    "hint.battery_action"   to "Fon faoliyatiga ruxsat",
    "hint.autostart"        to "Xiaomi, Samsung, Huawei va shunga o‘xshash telefonlarda Vortex reboot’dan keyin tiklanib, ulanib turishi uchun unga avto-ishga tushish (yoki “hech uxlamaydigan”) ruxsatini bering.",
    "hint.autostart_action" to "Autostart sozlamalari",
    "hint.notif_access"     to "Bildirishnoma kirishini yoqing — shunda Vortex nima o'ynayotganini aniq biladi va quloqchinni to'g'ri almashtiradi (aks holda qo'polroq aniqlovchiga tushadi).",
    "hint.notif_access_action" to "Bildirishnoma kirishini yoqish",
    "common.later"          to "Keyinroq",
    "notes.title"           to "Eslatmalar",
    "notes.all"             to "Hammasi",
    "notes.notes"           to "Qaydlar",
    "notes.todos"           to "Vazifalar",
    "notes.new_note"        to "Yangi qayd",
    "notes.new_todo"        to "Yangi vazifa",
    "notes.empty"           to "Hozircha eslatma yo'q",
    "notes.untitled"        to "Sarlavhasiz",
    "notes.title_placeholder" to "Sarlavha",
    "notes.todo_placeholder"  to "Nima qilish kerak?",
    "notes.body_placeholder"  to "Biror narsa yozing…",
    "notes.delete"          to "O'chirish",
    "notes.add_reminder"    to "Eslatma qo'shish",
    "notes.clear_reminder"  to "Eslatmani o'chirish",
    "notes.add_todo"        to "Vazifa qo'shish",
    "notes.empty_todos"     to "Hozircha vazifa yo'q",
    "notes.todos_done"      to "%d / %d bajarildi",
    "notes.tap_complete"    to "Bajarish uchun doirani bosing",
    "hint.dismiss"          to "Tushunarli",
    "settings.title"        to "Sozlamalar",
    "settings.sec_appearance" to "Ko'rinish",
    "settings.sec_continuity" to "Uzluksizlik",
    "settings.sec_device"     to "Qurilma",
    "settings.language"     to "Til",
    "settings.theme"        to "Mavzu",
    "settings.theme_dark"   to "Qora",
    "settings.theme_light"  to "Oq",
    "settings.smart_switch"      to "Aqlli almashtirish",
    "settings.smart_switch_hint" to "Quloqchin media boshlangan qurilmaga ko‘chsin",
    "settings.notif_mirror"      to "Bildirishnoma uzatish",
    "settings.notif_mirror_hint" to "Telefon bildirishnomalari laptopda ko‘rinsin",
    "settings.peer_notif"        to "Laptop bildirishnomalari",
    "settings.peer_notif_hint"   to "Laptop bildirishnomalari shu telefonda ko‘rinsin",
    "settings.clipboard_sync"       to "Clipboard sinxron",
    "settings.clipboard_sync_hint"  to "Nusxalangan matnni laptop bilan ikki tomonlama ulashish",
    "settings.file_auto_accept"      to "Laptopdan fayllarni avtomatik qabul qilish",
    "settings.file_auto_accept_hint" to "Laptop yuborgan fayllarni so‘ramasdan saqlash. Ularni faqat bog‘langan laptopingiz yubora oladi.",
    "settings.clipboard_adb_title"  to "Telefon→laptop avtomatik bo‘lsin",
    "settings.clipboard_adb_body"   to "Android fonda clipboard o‘qishni bloklaydi. Tile’siz nusxalash uchun kompyuterdan (USB debugging yoniq) bir marta shuni bajaring:",
    "settings.clipboard_auto_on"    to "Avtomatik — nusxa tile’siz sinxron bo‘ladi",
    "settings.on"           to "Yoniq",
    "settings.off"          to "O‘chiq",
    "settings.done"         to "Tayyor",
)

private val RU = mapOf(
    "app.title"            to "Vortex",
    "app.tagline"          to "Безопасный мост между Linux и Android",
    "device.this"          to "Это устройство",
    "device.linux"         to "Linux ноутбук",
    "device.android"       to "Android телефон",
    "device.earbuds"       to "Наушники",
    "device.paired_badge"  to "%d сопряжено",
    "device.loading"       to "загрузка идентификатора…",
    "peers.title"          to "Сопряжённые устройства",
    "peers.empty"          to "Пока нет устройств. Откройте Vortex на Linux рядом — он появится здесь автоматически.",
    "peers.forget_all"     to "Забыть все",
    "peers.online"         to "Подключено",
    "peers.offline"        to "Отключено",
    "peers.forget_title"   to "Забыть устройство",
    "peers.forget_body"    to "Перестать доверять %s? Чтобы вновь подключиться, потребуется повторное сопряжение.",
    "peers.forget_confirm" to "Забыть",
    "earbuds.not_connected" to "Не подключены",
    "earbuds.on_local"     to "Подключены к телефону",
    "earbuds.on_peer"      to "Подключены к ноутбуку",
    "earbuds.use_here"     to "Слушать на телефоне",
    "earbuds.handoff_soon" to "Скоро будет",
    "earbuds.add"          to "Добавить наушники",
    "earbuds.add_hint"     to "Нажмите, чтобы выбрать устройство",
    "earbuds.add_modal_hint" to "Выберите Bluetooth-устройство, которое Vortex будет отслеживать. Оно останется на главном экране даже когда отключено.",
    "earbuds.scanning"     to "Поиск Bluetooth-устройств…",
    "earbuds.scan_done"    to "Выберите устройство",
    "earbuds.scan_empty"   to "Устройства не найдены. Переведите наушники в режим сопряжения и нажмите Повторить.",
    "earbuds.rescan"       to "Повторить",
    "earbuds.now_connected" to "подключено",
    "earbuds.remove"       to "Убрать из Vortex",
    "earbuds.remove_body"  to "Карточка наушников исчезнет. Сопряжение Bluetooth не меняется.",
    "earbuds.long_press_hint" to "Долгое нажатие — убрать",
    "switch.bring_title"   to "Передать наушники сюда?",
    "switch.bring_body"    to "Ноутбук отключит их, затем подключится этот телефон.",
    "switch.bring_confirm" to "На этот телефон",
    "switch.send_title"    to "Отправить наушники ноутбуку?",
    "switch.send_body"     to "Телефон отключит их, затем подключится ноутбук.",
    "switch.send_confirm"  to "На ноутбук",
    "switch.cancel"        to "Отмена",
    "cast.kind_title"      to "Показать экран ноутбука",
    "cast.kind_extend"     to "Дополнительный экран",
    "cast.kind_extend_hint" to "Второй экран для ноутбука — окна можно перетаскивать на телефон",
    "cast.kind_mirror"     to "Зеркало экрана",
    "cast.kind_mirror_hint" to "Показывает то, что уже на экране ноутбука",
    "switch.send_menu"     to "На ноутбук",
    "switch.in_progress"   to "Переключение…",
    "switch.failed"        to "Не удалось: %s",
    "scan.close"           to "Закрыть",
    "discover.title"       to "Поиск",
    "discover.discoverable" to "Виден",
    "discover.discoverable_hint" to "Откройте Vortex на Linux ноутбуке рядом.",
    "discover.idle"         to "Нажмите Начать чтобы стать видимым.",
    "pair.start"           to "Начать сопряжение",
    "pair.resume"          to "Продолжить",
    "pair.stop"            to "Стоп",
    "pair.stop_window"     to "Закрыть окно",
    "pair.starting"        to "Запуск…",
    "pair.try_again"       to "Повторить",
    "pair.caption_idle"    to "Фоновый сервис работает в режиме доверенного присутствия.",
    "pair.caption_no_trust" to "Нажмите, чтобы открыть окно сопряжения на 60 секунд.",
    "pair.caption_starting" to "Запуск GATT сервера…",
    "pair.caption_window"   to "Окно сопряжения открыто. Найдите это устройство с Linux.",
    "pair.caption_presence" to "Доступно сопряжённым устройствам • новый токен каждые 60с.",
    "pair.error"            to "Ошибка: %s",
    "sas.title"             to "Запрос сопряжения",
    "sas.body"              to "Linux устройство хочет сопрячься с этим телефоном. Убедитесь, что эти три эмодзи совпадают с ноутбуком, и подтвердите.",
    "sas.approve"           to "Подтвердить",
    "sas.reject"            to "Отклонить",
    "hint.bluetooth_off"    to "Bluetooth выключен — Vortex связывается по энергоэффективному Bluetooth (он не разряжает батарею). Включите, чтобы подключиться.",
    "hint.bluetooth_off_action" to "Включить Bluetooth",
    "hint.battery"          to "Оптимизация батареи включена — Android может убить Vortex когда экран гаснет.",
    "hint.battery_action"   to "Разрешить фоновую активность",
    "hint.autostart"        to "На Xiaomi, Samsung, Huawei и подобных телефонах разрешите Vortex автозапуск (или «не усыплять»), чтобы он переподключался и оставался на связи после перезагрузки.",
    "hint.autostart_action" to "Открыть настройки автозапуска",
    "hint.notif_access"     to "Дайте доступ к уведомлениям, чтобы Vortex точно определял, что играет, и переключал наушники (иначе — грубый детектор).",
    "hint.notif_access_action" to "Дать доступ к уведомлениям",
    "common.later"          to "Позже",
    "notes.title"           to "Заметки",
    "notes.all"             to "Все",
    "notes.notes"           to "Заметки",
    "notes.todos"           to "Задачи",
    "notes.new_note"        to "Новая заметка",
    "notes.new_todo"        to "Новая задача",
    "notes.empty"           to "Пока нет заметок",
    "notes.untitled"        to "Без названия",
    "notes.title_placeholder" to "Заголовок",
    "notes.todo_placeholder"  to "Что нужно сделать?",
    "notes.body_placeholder"  to "Напишите что-нибудь…",
    "notes.delete"          to "Удалить",
    "notes.add_reminder"    to "Добавить напоминание",
    "notes.clear_reminder"  to "Убрать напоминание",
    "notes.add_todo"        to "Добавить задачу",
    "notes.empty_todos"     to "Пока нет задач",
    "notes.todos_done"      to "%d из %d выполнено",
    "notes.tap_complete"    to "Нажмите кружок, чтобы выполнить",
    "hint.dismiss"          to "Понятно",
    "settings.title"        to "Настройки",
    "settings.sec_appearance" to "Внешний вид",
    "settings.sec_continuity" to "Непрерывность",
    "settings.sec_device"     to "Устройство",
    "settings.language"     to "Язык",
    "settings.theme"        to "Тема",
    "settings.theme_dark"   to "Тёмная",
    "settings.theme_light"  to "Светлая",
    "settings.smart_switch"      to "Умное переключение",
    "settings.smart_switch_hint" to "Наушники переходят на устройство, где включили звук",
    "settings.notif_mirror"      to "Зеркалирование уведомлений",
    "settings.notif_mirror_hint" to "Показывать уведомления телефона на ноутбуке",
    "settings.peer_notif"        to "Уведомления ноутбука",
    "settings.peer_notif_hint"   to "Показывать уведомления ноутбука на этом телефоне",
    "settings.clipboard_sync"       to "Синхронизация буфера",
    "settings.clipboard_sync_hint"  to "Обмен скопированным текстом с ноутбуком в обе стороны",
    "settings.file_auto_accept"      to "Автоприём файлов с ноутбука",
    "settings.file_auto_accept_hint" to "Сохранять файлы с ноутбука без подтверждения. Отправить их может только сопряжённый ноутбук.",
    "settings.clipboard_adb_title"  to "Сделать телефон→ноутбук автоматическим",
    "settings.clipboard_adb_body"   to "Android блокирует чтение буфера в фоне. Выполните один раз с компьютера (USB-отладка вкл), чтобы копировать без плитки:",
    "settings.clipboard_auto_on"    to "Автоматически — копии синхронизируются без плитки",
    "settings.on"           to "Вкл",
    "settings.off"          to "Выкл",
    "settings.done"         to "Готово",
)

private val STRINGS: Map<VortexLocale, Map<String, String>> = mapOf(
    VortexLocale.English to EN,
    VortexLocale.Uzbek   to UZ,
    VortexLocale.Russian to RU,
)
